---
title: "MLE problem solutions"
output: html_document
---

## HW 1, Question 6

The observed data is $1, 1, 3, 7, 2, 4, 3$. So, our likelihood is

$P(Y = 1) \cdot P(Y = 1) \cdot P(Y = 3) \cdot P(Y = 7) \cdot P(Y = 2) \cdot P(Y = 4) \cdot P(Y = 3)$

We are told that $P(Y = y) = (1 - \pi_0)^{y-1} \pi_0$. So, $P(Y = 1) = \pi_0$, $P(Y = 3) = (1 - \pi_0)^2 \pi_0$, $P(Y = 7) = (1 - \pi_0)^6 \pi_0$, etc. Plugging everything in, we get

$L(\widehat{\pi}_0) = (\widehat{\pi}_0)^7 (1 - \widehat{\pi}_0)^{14}$


When $\widehat{\pi}_0 = 0.6$,

$L(0.6) = (0.6)^7(1 - 0.6)^{14} = 7.51 \times 10^{-8}$


## HW 1, Question 7

$L(\widehat{\pi}_0) = (\widehat{\pi}_0)^7 (1 - \widehat{\pi}_0)^{14}$

$\log L(\widehat{\pi}_0) = 7 \log (\widehat{\pi}_0) + 14 \log (1 - \widehat{\pi}_0)$


## HW 1, Question 8

$\dfrac{d}{d \widehat{\pi}_0} \log L(\widehat{\pi}_0) = \dfrac{7}{\widehat{\pi}_0} - \dfrac{14}{1 - \widehat{\pi}_0} = 0$

$\dfrac{7}{\widehat{\pi}_0} = \dfrac{14}{1 - \widehat{\pi}_0}$

$\dfrac{1 - \widehat{\pi}_0}{\widehat{\pi}_0} = 2$

$\dfrac{1}{\widehat{\pi}_0} = 3$

$\widehat{\pi}_0 = \dfrac{1}{3}$

### Lab 2, Question 12

First, we take the log of the likelihood. Remember that $\log \left(\prod \limits_{i=1}^n a_i \right) = \sum \limits_{i=1}^n \log(a_i)$, so the log likelihood is:

$\log L(\widehat{\lambda}) = \sum \limits_{i=1}^n \log \left( \dfrac{\widehat{\lambda}^{Y_i} e^{-\widehat{\lambda}}}{Y_i!} \right)$

Now, using rules for logs, $\log \left( \dfrac{\widehat{\lambda}^{Y_i} e^{-\widehat{\lambda}}}{Y_i!} \right) = Y_i \log(\widehat{\lambda}) - \widehat{\lambda} - \log(Y_i!)$. So, our log likelihood is

$\log L(\widehat{\lambda}) = \sum \limits_{i=1}^n \left( Y_i \log(\widehat{\lambda}) - \widehat{\lambda} - \log(Y_i!) \right)$

Differentiating, we get

$\dfrac{d}{d \widehat{\lambda}} \log L(\widehat{\lambda}) = \sum \limits_{i=1}^n \left( \dfrac{Y_i}{\widehat{\lambda}} - 1 \right)$

Setting to 0, $\sum \limits_{i=1}^n \left( \dfrac{Y_i}{\widehat{\lambda}} - 1 \right)$, so

$\sum \limits_{i=1}^n \dfrac{Y_i}{\widehat{\lambda}} = \sum \limits_{i=1}^n 1 = n$.

And solving for $\widehat{\lambda}$, we get

$\widehat{\lambda} = \frac{1}{n} \sum \limits_{i=1}^n Y_i$