---
title: "Class Activity, October 30"
output: 
  tufte::tufte_html:
    css: "lab.css"
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

We have data on prices and other information for 1561 rentals in Chicago, Illinois. Our goal is to model the relationship between price and overall satisfaction score. The information comes from 43 neighborhoods, and we have information on between 25 to 50 rentals per neighborhood. The variables we will be using are as follows:

* `price`: The price in US dollars of a one night rental
* `overallSatisfaction`: an average satisfaction score, given as numbers between 2.5 and 5
* `neighborhood`: the neighborhood in which the rental is located

1. Why is a mixed effects model useful for modeling the relationship between price and overall satisfaction in this data?

2. Write down the population linear mixed effects model for the relationship between price (the response) and overall satisfaction (the predictor), accounting for neighborhood with a random effect. *Note that satisfaction is a quantitative predictor, not a categorical predictor*.

3. Identify the effect of interest, the group effect, and the individual effect.

4. What assumptions does our linear mixed effects model make?