---
title: "Class Activity, November 16"
output: 
  tufte::tufte_html:
    css: "lab.css"
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

Anxiety can affect musicians before performances, and can negatively affect their ability to play and their emotional state. In a [2010 study](https://journals.sagepub.com/doi/10.1177/1948550610370492), researchers examined anxiety in 37 undergraduate music majors. For each musician, data was collected on anxiety levels before different performances (between 2 and 15 performances were measured for each musician). Each row in the data represents one performance, and variables include

* `id`: a unique identifier for the musician
* `na`: negative affect score (a measure of anxiety)
* `large`: whether the musician was performing as part of a large ensemble (large = 1), or as part of a small ensemble or solo (large = 0)

Researchers hypothesize that anxiety will be lower before large ensemble performance (because the student is one of many performers). Researchers also expect that anxiety levels will vary from student to student, and the difference in performance anxiety between large and small performances will also vary from person to person.

1. Mixed effects models are useful when there are group effects in our data. What are the groups in the data, and what are the observations within each group?

2. What mixed effects model should the researchers use to investigate their hypothesis?

3. Interpret the fixed effects and random effects in the model.